openai:
  api_key: ""

embedding:
  provider: "azure"
  azure_endpoint: "https://abder-mbwdetrn-eastus2.cognitiveservices.azure.com/"
  azure_deployment: "text-embedding-3-large-testing"
  azure_api_version: "2024-12-01-preview"
  azure_api_key: "9JZyUj0kbuvfHrcBSUXAwCo4uUVFjvHaXHzvFydFJ0RfIwEs1UkgJQQJ99BFACHYHv6XJ3w3AAAAACOGieFE"

chat:
  provider: "azure"
  azure_endpoint: "https://abder-mbwdetrn-eastus2.cognitiveservices.azure.com/"
  azure_deployment: "gpt-4o-testing"
  azure_api_version: "2024-12-01-preview"
  azure_api_key: "9JZyUj0kbuvfHrcBSUXAwCo4uUVFjvHaXHzvFydFJ0RfIwEs1UkgJQQJ99BFACHYHv6XJ3w3AAAAACOGieFE"
